### ISSUE TITLE
Not working ):

### ISSUE THREAD

**Issue by lBrunol** [phproberto/vscode-php-getters-setters#1]
Hello, 

When I try to generate nothing happens in all the options. Also no error message appears.

I'm using VS Code in Ubuntu 16.04. The extension version is 1.0.5.

PS: Sorry for english, is it from google translate.

Thanks.

**Comment by phproberto** [comment]
I'm using Ubuntu 16.04 as the development machine so it should be ok. I will do a full round of testing to check if there is an issue but can you send me as much information as you can about the issue? Things like Visual Studio Code version and maybe a screenshot of the failure?

**Comment by lBrunol** [comment]
Hello,

Sorry for the delay.

Simply nothing happens. See in the GIF.

My VS Code version is 1.19.1.

![demonstracao](https://user-images.githubusercontent.com/11487729/34989987-9ba142c8-faab-11e7-9a6a-0e9ff226bf55.gif)

Thanks.

**Comment by h4de5** [comment]
not working for me neither.
when access via context menu, nothing happends.
if i call via 

command 'phpGettersSetters.insertGetterAndSetter' not found
VSC Insider 1.21, win10, x64, plugin: 1.0.5

**Comment by Belz3buth** [comment]
same for me
thx <3

**Comment by phproberto** [comment]
I think it may be related with having more than one class in the same file. I'm now trying to improve file parsing. I will write a message here later. 

Thanks everybody for taking the time to send feedback ❤️

**Comment by phproberto** [comment]
Finally I was able to detect the issue thanks to @lBrunol gif. The issue was that the parser was not able to detect the closing line in files with indentation.

I've release v1.0.6 that already contains the fix. Can you confirm it works now?

Thanks again!

**Comment by phproberto** [comment]
Very strange @h4de5. I've used exactly that code and it works.

I've applied a fix like based on this reported issue:
https://github.com/Microsoft/vscode/issues/15837

Can you please: 
* Uninstall extension.
* Install extension (it should be v1.0.7).
* Check if now works.

Apparently not shipping the node_modules can cause such issues. See also:

https://github.com/Ikuyadeu/vscode-R/issues/6

Crossing fingers! 🤞

**Comment by h4de5** [comment]
didn't work with 1.0.7 - wanted to try it on another computer. saw that there was another update to 1.1 - tried it again and it works fine now :)
confirming functionality on VSC Insider 1.21, win10, x64, plugin: 1.1

thanks!

**Comment by DeepSnowNeeL** [comment]
Same for me, it doesn't work 
The php file is a doctrine entity so nothing complicated to parse. 

command 'phpGettersSetters.insertGetterAndSetter' not found

> Windows 10 (PS: it is working great on my Mac)
> code -v
1.22.2
3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
ia32

**Comment by flleo** [comment]
Uninstall the extension, install again, close Visual Code and start again , works for me :)

**Comment by KhalidHayKay** [comment]
> Uninstall the extension, install again, close Visual Code and start again , works for me :)

worked for me also.
