### ISSUE TITLE
Fluent accessors

### ISSUE THREAD

**Issue by PapsOu** [phproberto/vscode-php-getters-setters#10]
Hello,

Is there any way to disable the fluent accessors (return self in setters) using a configuration key ?

**Comment by BreizhReloaded** [comment]
Hi @PapsOu,

You may be interested by [this thread](https://github.com/phproberto/vscode-php-getters-setters/issues/3). I'm also looking for a way to remove the return self thing.

**Comment by phproberto** [comment]
Hey,

I'm currently developing support for file templates so we save having XX configuration options. I will finish it today/tomorrow. 

Thanks for your suggestions. you are awesome!

**Comment by phproberto** [comment]
This can now be done with custom templates. Please check section in readme:

https://github.com/phproberto/vscode-php-getters-setters#custom-templates

Basically you have to create 2 template files (one for the getter template and one for the setter template). There are 2 examples there.

Thanks everybody!
