### ISSUE TITLE
option for disable the comment

### ISSUE THREAD

**Issue by SaveYourTime** [phproberto/vscode-php-getters-setters#11]
If there is an option for option for disable the comment will be great.

<img width="215" alt="2018-04-22 8 21 59" src="https://user-images.githubusercontent.com/35715664/39090042-6fc0521a-4606-11e8-82fe-a5ca35630271.png">

**Comment by phproberto** [comment]
I'm currently working in adding customisable templates. I hope to finish it today/tomorrow and release a new version.

**Comment by phproberto** [comment]
This can noe be done with custom templates. Please check custom templates section in readme:

https://github.com/phproberto/vscode-php-getters-setters#custom-templates

Basically you have to create 2 template files (one for the getter template and one for the setter template). There are 2 examples there.

Thanks for your feedback!
