### ISSUE TITLE
Sample setter.js template has null

### ISSUE THREAD

**Issue by laurensdelombaert** [phproberto/vscode-php-getters-setters#12]
I am able to successfully customize a getter template, but generating setters after creating/using the example template doesn't seem to work properly. 

Result of generating a setter:

![setter](https://user-images.githubusercontent.com/32126029/39675591-9278b164-515d-11e8-9627-253d709ca918.png)

**Comment by phproberto** [comment]
Can you please share the property definition you are using to be able to reproduce the issue and update demo setter?

**Comment by phproberto** [comment]
Hi @laurensdelombaert I have published a new version (v1.2.3) that ensures that null is detected as a pseudo type (cannot be used for type hinting). I also have updated templates examples to show how you can skip null values thanks to template literals.

Thanks for your feedback!
