### ISSUE TITLE
Getters think the type of null when 1 line doc blocks are used

### ISSUE THREAD

**Issue by jordanpartridge** [phproberto/vscode-php-getters-setters#15]
`/** @var int|null */`

property.getType = null

```
/** 
 *  @var int|null 
 */

```
property.getType = int|null

also would be good to have some support for this type or null  syntax as the team I work on often will add the return type in the function signature

like this

```
/**
 *  @return string|nul};
 * /
public  function  getProperty():  ?string    
```
where the '?' would denote a possible null value    and  string without question mark wouldn't allow a null.

**Comment by romualdoviana** [comment]
module.exports = (property) => `
        /**
         * ${property.getterDescription()}
         *
         * @return  ${property.getType() ? property.getType() : 'mixed'}
         */
        public function ${property.getterName()}():${property.getType() ? (property.getType().includes('|')?
        '?'+property.getType().split('|')[0]:property.getType()) : 'mixed'}
        {
                return $this->${property.getName()};
        }

`
