### ISSUE TITLE
Configure the template

### ISSUE THREAD

**Issue by mcunha98** [phproberto/vscode-php-getters-setters#3]
Like in Eclipse, not is possible to create a way to configure the template ?
For example I don't use return on SET some property and also, I don't put comments in get/set methods for all properties

**Comment by phproberto** [comment]
Hi @mcunha98 ,

I tried to use snippets for templates so people could overwrite them but apparently that's not an allowed usage of snippets on Visual Code Studio. I will double check it today to see if I can find a way to customise templates without having to add XX parameters for each thing. 

I will write my findings here this week.

Thanks for using this extension.

**Comment by BreizhReloaded** [comment]
Hi @phproberto,

Do you have any news on that point? I really love your extension, but I'd like to be able to customize the template as well.

Huge thanks for your work!

**Comment by phproberto** [comment]
I think I finally found a way to do it on a clean way. I hope to finish it today/tomorrow and release a new version.

Thanks for your feedback!

**Comment by BreizhReloaded** [comment]
How soon! That's really nice, thank you @phproberto!

**Comment by phproberto** [comment]
This is now done. Please check custom templates section in readme:

https://github.com/phproberto/vscode-php-getters-setters#custom-templates

Basically you have to create 2 template files (one for the getter template and one for the setter template). There are 2 examples there.

Thanks everybody!

**Comment by BreizhReloaded** [comment]
It works perfectly. A huge thank @phproberto!

**Comment by phproberto** [comment]
Cool! Thanks for checking it @BreizhReloaded :1st_place_medal:
