### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by PapsOu** [phproberto/vscode-php-getters-setters#9]
Hello,

Sometimes, VSCode throws this Exception : `command 'phpGettersSetters.insertGetterAndSetter' not found`

I really don't know what action is « killing » the extension's feature.

![vscode-php-getter-setter](https://user-images.githubusercontent.com/5792207/38730691-d37e6f80-3f17-11e8-9067-18e045db9a06.gif)

Restarting VSCode seems solving the problem.

```
Version 1.22.1
Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
Date 2018-04-06T00:24:49.616Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

Running on Ubuntu :
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

**Comment by SaveYourTime** [comment]
same here

**Comment by phproberto** [comment]
Have you tried to reinstall the extension? I've searched and apparently such issues happen when there is a corrupted install (caused by restarting vscode when an update is being installed and things like that). I'd try a full uninstall and install.

Thanks for your feedback!

**Comment by AdamHamdi** [comment]
close your vscode and reopen  again ...

**Comment by Acutapugione** [comment]
I closed and reopen vscode, it works.
